DROP TABLE IF EXISTS Windows;
DROP TABLE IF EXISTS WindowsObservation;
DROP TABLE IF EXISTS AWObservation;
DROP TABLE IF EXISTS AFKObservation;

CREATE TABLE Windows (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT,
    process TEXT NOT NULL
);

CREATE TABLE WindowsObservation (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME NOT NULL,
    window_id INTEGER NOT NULL,
    FOREIGN KEY (window_id) REFERENCES Windows(id)
);

CREATE TABLE AWObservation (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME NOT NULL,
    window_id INTEGER,
    FOREIGN KEY (window_id) REFERENCES Windows(id)
);

CREATE TABLE AFKObservation (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME NOT NULL,
    is_afk BOOLEAN NOT NULL
);
